task_cspell
dev-KPI/messenger-backend pull request #25
Opened 2023-10-18 08:36 UTC by dEdmishka

### added gitattributes file

### added cspell:
- cspell now in project!
- project-words.txt is dictionary for new words
- cspell.json is config file for cspell
- npm run cspell used for general analysis of words of src folder
- npm run cspell:check checks for typo and suggest replacement for user
- npm run cspell:apply add words to dictionary
- cspell also work in pre-commit!

2023-10-18 09:33 UTC, firehawk89 approved these changes
Looks good

2023-10-18 11:02 UTC, DemianParkhomenko requested changes
Please rebase and fix several comments
Good job!

![good-job-2](https://github.com/dev-KPI/messenger-backend/assets/95881717/d13c9fe7-beef-4919-b860-05c1856f426f)

2023-10-20 15:52 UTC, dEdmishka commented on .lintstagedrc.js
> +  '*.{js,ts}': () => 'npm run cspell',
Resolved!

2023-10-20 15:52 UTC, dEdmishka commented on .lintstagedrc.js
Added new util file to src/utils folder with this code)

2023-10-20 15:52 UTC, dEdmishka commented on package.json
> +    "cspell:check": "cspell --no-progress --show-suggestions --show-context  \"src/**/*.js\""
Shorted!

2023-10-21 11:17 UTC, dEdmishka reviewed
review is finished

2023-10-22 18:05 UTC, DemianParkhomenko approved these changes

2023-10-22 18:17 UTC, merged